# Generated by Django 3.0.8 on 2020-11-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisa', '0002_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
