# Generated by Django 3.0.8 on 2020-11-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='antara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='detik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='kompas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=18)),
            ],
        ),
    ]
